name: starter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.9
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  graphql_flutter: ^5.1.2
  jwt_decoder: ^2.0.1
  get: ^4.6.6
  firebase_auth: ^4.17.0
  material_symbols_icons: ^4.2718.0
  firebase_core: ^2.25.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: ShantellSans
      fonts:
       - asset: assets/font/ShantellSans/regular.ttf
       - asset: assets/font/ShantellSans/italic.ttf
         style: italic

    - family: RobotoCondensed
      fonts:
       - asset: assets/font/RobotoCondensed/regular.ttf
       - asset: assets/font/RobotoCondensed/italic.ttf
         style: italic