// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAk_MDTrjyALC_X_2x0fErVd-FvE0qsI',
    appId: '1:340570457104:web:eb4c5c62ae385c027a7695',
    messagingSenderId: '340570457104',
    projectId: 'my-flutter-starter',
    authDomain: 'my-flutter-starter.firebaseapp.com',
    storageBucket: 'my-flutter-starter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokyMnIDWM3M7S4vN420og8o9VX2jrch0',
    appId: '1:340570457104:android:a8a1fa11289970867a7695',
    messagingSenderId: '340570457104',
    projectId: 'my-flutter-starter',
    storageBucket: 'my-flutter-starter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqREr5g4C_n1Dy1SylYywf3_xjOLt3Vto',
    appId: '1:340570457104:ios:9ff0d705a55395e97a7695',
    messagingSenderId: '340570457104',
    projectId: 'my-flutter-starter',
    storageBucket: 'my-flutter-starter.appspot.com',
    iosBundleId: 'com.example.starter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqREr5g4C_n1Dy1SylYywf3_xjOLt3Vto',
    appId: '1:340570457104:ios:e4daf955714e34a97a7695',
    messagingSenderId: '340570457104',
    projectId: 'my-flutter-starter',
    storageBucket: 'my-flutter-starter.appspot.com',
    iosBundleId: 'com.example.starter.RunnerTests',
  );
}
